# ------------------------------------------------
# deploy workflow
# ------------------------------------------------
name: Deploy to GitHub Pages

# ------------------------------------------------
# this workflow will run
# • anytime a commit is pushed to the main branch
# ------------------------------------------------
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    # --------------------------------------------
    # workflow runs on an ubuntu image
    # --------------------------------------------
    runs-on: ubuntu-latest

    # --------------------------------------------
    # define the steps we want to run
    # --------------------------------------------
    steps:
      # ------------------------------------------
      # check out files tracked by git
      # ------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3

      # ------------------------------------------
      # find node version
      # ------------------------------------------
      - name: Determine node version
        run: test -f .nvmrc && echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      # ------------------------------------------
      # setup node env
      # ------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      # ------------------------------------------
      # setup pnpm
      # ------------------------------------------
      - name: Setup pnpm
        run: npm install -g pnpm

      # ------------------------------------------
      # install dependencies
      # ------------------------------------------
      - name: Install dependencies
        run: pnpm install

      # ------------------------------------------
      # check formatting
      # ------------------------------------------
      - name: Run formatter
        run: pnpm format

      # ------------------------------------------
      # check linting
      # ------------------------------------------
      - name: Run linter
        run: pnpm lint

      # ------------------------------------------
      # run unit tests
      # ------------------------------------------
      - name: Run unit tests
        run: pnpm test

      # ------------------------------------------
      # build assets
      # ------------------------------------------
      - name: Build assets
        run: pnpm export

      # ------------------------------------------
      # deploy: this step pushes our dist folder
      # to github pages
      # ------------------------------------------
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./out
